version: '3'
services:
    mysql-5.7:
        container_name: mysql-5.7
        image: library/mysql:5.7
        ports:
            - 3357:3306
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            TZ: Europe/Moscow
        volumes:
            - "${PWD}:/mysql-5.7:cached"
            - "mysql_dump:/docker-entrypoint-initdb.d"
            - "./mysqld.cnf:/etc/mysql/conf.d/custom-mysqld.cnf:cached"